# Etapa 1: Contenedor de Desarrollo con VSCode
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-18-bullseye
#mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye
#mcr.microsoft.com/vscode/devcontainers/typescript-node
#mcr.microsoft.com/vscode/devcontainers/javascript-node:18

RUN npm install -g @angular/cli